:This is a basic workflow to help you get started with Actions

name: seksun1/seksun1

 :controls when the word's will run on google to
</ref>automatic workking to gat URL: https://www.seksun_komsan.org.co.th
 :Triggers the workflow on push or pull request events but only for the main branch
 
    branches: punpui877@hotmail.com
  pull_request:https://www.seksun_komsan.org.co.th
    branches:github.com

 :Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:link punpui877@hotmail.com
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions

      # Runs a single command using the runners shell
      - name: Run a one-line javascript
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line javascript
        run:from by google group
          echo Add other actions to build,
          echo test, and deploy your project:group all google

        :and:project: commission contact by all new move start wap Url:https://www.seksun_komsan.org.co.th/
